set(_CATKIN_CURRENT_PACKAGE "ackermann_msgs")
set(ackermann_msgs_VERSION "1.0.1")
set(ackermann_msgs_MAINTAINER "Jack O'Quin <jack.oquin@gmail.com>")
set(ackermann_msgs_PACKAGE_FORMAT "1")
set(ackermann_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(ackermann_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(ackermann_msgs_BUILDTOOL_DEPENDS "catkin")
set(ackermann_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(ackermann_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(ackermann_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(ackermann_msgs_TEST_DEPENDS )
set(ackermann_msgs_DOC_DEPENDS )
set(ackermann_msgs_DEPRECATED "")