set(_CATKIN_CURRENT_PACKAGE "fake_localization")
set(fake_localization_VERSION "1.13.1")
set(fake_localization_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(fake_localization_PACKAGE_FORMAT "1")
set(fake_localization_BUILD_DEPENDS "angles" "roscpp" "rosconsole" "nav_msgs" "geometry_msgs" "tf" "message_filters" "rospy")
set(fake_localization_BUILD_EXPORT_DEPENDS "roscpp" "rosconsole" "nav_msgs" "geometry_msgs" "tf" "message_filters" "rospy")
set(fake_localization_BUILDTOOL_DEPENDS "catkin")
set(fake_localization_BUILDTOOL_EXPORT_DEPENDS )
set(fake_localization_EXEC_DEPENDS "roscpp" "rosconsole" "nav_msgs" "geometry_msgs" "tf" "message_filters" "rospy")
set(fake_localization_RUN_DEPENDS "roscpp" "rosconsole" "nav_msgs" "geometry_msgs" "tf" "message_filters" "rospy")
set(fake_localization_TEST_DEPENDS )
set(fake_localization_DOC_DEPENDS )
set(fake_localization_DEPRECATED "")