set(_CATKIN_CURRENT_PACKAGE "image_geometry")
set(image_geometry_VERSION "1.12.2")
set(image_geometry_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(image_geometry_PACKAGE_FORMAT "2")
set(image_geometry_BUILD_DEPENDS "opencv3" "sensor_msgs")
set(image_geometry_BUILD_EXPORT_DEPENDS "sensor_msgs")
set(image_geometry_BUILDTOOL_DEPENDS "catkin")
set(image_geometry_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(image_geometry_BUILDTOOL_EXPORT_DEPENDS )
set(image_geometry_EXEC_DEPENDS "opencv3")
set(image_geometry_RUN_DEPENDS "opencv3" "sensor_msgs")
set(image_geometry_TEST_DEPENDS )
set(image_geometry_DOC_DEPENDS "dvipng" "texlive-latex-extra")
set(image_geometry_DEPRECATED "")