set(image_geometry_SETUP_PY_VERSION "1.12.2")
set(image_geometry_SETUP_PY_SCRIPTS "")
set(image_geometry_SETUP_PY_PACKAGES "image_geometry")
set(image_geometry_SETUP_PY_PACKAGE_DIRS "src/image_geometry")
set(image_geometry_SETUP_PY_MODULES "")
set(image_geometry_SETUP_PY_MODULE_DIRS "")