set(_CATKIN_CURRENT_PACKAGE "imu_odom")
set(imu_odom_VERSION "0.0.0")
set(imu_odom_MAINTAINER "Kazu Otani <kazuotani14@gmail.com>")
set(imu_odom_PACKAGE_FORMAT "1")
set(imu_odom_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "tf" "nav_msgs")
set(imu_odom_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf")
set(imu_odom_BUILDTOOL_DEPENDS "catkin")
set(imu_odom_BUILDTOOL_EXPORT_DEPENDS )
set(imu_odom_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf")
set(imu_odom_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf")
set(imu_odom_TEST_DEPENDS )
set(imu_odom_DOC_DEPENDS )
set(imu_odom_DEPRECATED "")