set(_CATKIN_CURRENT_PACKAGE "costmap_2d")
set(costmap_2d_VERSION "1.13.1")
set(costmap_2d_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(costmap_2d_PACKAGE_FORMAT "1")
set(costmap_2d_BUILD_DEPENDS "cmake_modules" "dynamic_reconfigure" "geometry_msgs" "laser_geometry" "map_msgs" "message_filters" "message_generation" "nav_msgs" "pcl_conversions" "pcl_ros" "pluginlib" "roscpp" "rostest" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "voxel_grid")
set(costmap_2d_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "geometry_msgs" "laser_geometry" "map_msgs" "message_filters" "message_runtime" "nav_msgs" "pcl_conversions" "pcl_ros" "pluginlib" "rosconsole" "roscpp" "rostest" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "voxel_grid")
set(costmap_2d_BUILDTOOL_DEPENDS "catkin")
set(costmap_2d_BUILDTOOL_EXPORT_DEPENDS )
set(costmap_2d_EXEC_DEPENDS "dynamic_reconfigure" "geometry_msgs" "laser_geometry" "map_msgs" "message_filters" "message_runtime" "nav_msgs" "pcl_conversions" "pcl_ros" "pluginlib" "rosconsole" "roscpp" "rostest" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "voxel_grid")
set(costmap_2d_RUN_DEPENDS "dynamic_reconfigure" "geometry_msgs" "laser_geometry" "map_msgs" "message_filters" "message_runtime" "nav_msgs" "pcl_conversions" "pcl_ros" "pluginlib" "rosconsole" "roscpp" "rostest" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "voxel_grid")
set(costmap_2d_TEST_DEPENDS "map_server" "rosbag")
set(costmap_2d_DOC_DEPENDS )
set(costmap_2d_DEPRECATED "")