set(_CATKIN_CURRENT_PACKAGE "nav_core")
set(nav_core_VERSION "1.13.1")
set(nav_core_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(nav_core_PACKAGE_FORMAT "1")
set(nav_core_BUILD_DEPENDS "std_msgs" "geometry_msgs" "costmap_2d" "tf")
set(nav_core_BUILD_EXPORT_DEPENDS "std_msgs" "geometry_msgs" "costmap_2d" "tf")
set(nav_core_BUILDTOOL_DEPENDS "catkin")
set(nav_core_BUILDTOOL_EXPORT_DEPENDS )
set(nav_core_EXEC_DEPENDS "std_msgs" "geometry_msgs" "costmap_2d" "tf")
set(nav_core_RUN_DEPENDS "std_msgs" "geometry_msgs" "costmap_2d" "tf")
set(nav_core_TEST_DEPENDS )
set(nav_core_DOC_DEPENDS )
set(nav_core_DEPRECATED "")