set(_CATKIN_CURRENT_PACKAGE "laser_ortho_projector")
set(laser_ortho_projector_VERSION "0.3.2")
set(laser_ortho_projector_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(laser_ortho_projector_PACKAGE_FORMAT "1")
set(laser_ortho_projector_BUILD_DEPENDS "roscpp" "nodelet" "sensor_msgs" "tf" "pcl_ros" "pcl_conversions" "geometry_msgs" "message_filters" "libpcl-all-dev")
set(laser_ortho_projector_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "sensor_msgs" "tf" "pcl_ros" "pcl_conversions" "geometry_msgs" "message_filters" "libpcl-all")
set(laser_ortho_projector_BUILDTOOL_DEPENDS "catkin")
set(laser_ortho_projector_BUILDTOOL_EXPORT_DEPENDS )
set(laser_ortho_projector_EXEC_DEPENDS "roscpp" "nodelet" "sensor_msgs" "tf" "pcl_ros" "pcl_conversions" "geometry_msgs" "message_filters" "libpcl-all")
set(laser_ortho_projector_RUN_DEPENDS "roscpp" "nodelet" "sensor_msgs" "tf" "pcl_ros" "pcl_conversions" "geometry_msgs" "message_filters" "libpcl-all")
set(laser_ortho_projector_TEST_DEPENDS )
set(laser_ortho_projector_DOC_DEPENDS )
set(laser_ortho_projector_DEPRECATED "")