set(_CATKIN_CURRENT_PACKAGE "ncd_parser")
set(ncd_parser_VERSION "0.3.2")
set(ncd_parser_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(ncd_parser_PACKAGE_FORMAT "1")
set(ncd_parser_BUILD_DEPENDS "roscpp" "sensor_msgs" "tf")
set(ncd_parser_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "tf")
set(ncd_parser_BUILDTOOL_DEPENDS "catkin")
set(ncd_parser_BUILDTOOL_EXPORT_DEPENDS )
set(ncd_parser_EXEC_DEPENDS "roscpp" "sensor_msgs" "tf")
set(ncd_parser_RUN_DEPENDS "roscpp" "sensor_msgs" "tf")
set(ncd_parser_TEST_DEPENDS )
set(ncd_parser_DOC_DEPENDS )
set(ncd_parser_DEPRECATED "")