set(_CATKIN_CURRENT_PACKAGE "clear_costmap_recovery")
set(clear_costmap_recovery_VERSION "1.13.1")
set(clear_costmap_recovery_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(clear_costmap_recovery_PACKAGE_FORMAT "1")
set(clear_costmap_recovery_BUILD_DEPENDS "cmake_modules" "roscpp" "tf" "costmap_2d" "nav_core" "pluginlib" "eigen")
set(clear_costmap_recovery_BUILD_EXPORT_DEPENDS "roscpp" "tf" "costmap_2d" "nav_core" "pluginlib" "eigen")
set(clear_costmap_recovery_BUILDTOOL_DEPENDS "catkin")
set(clear_costmap_recovery_BUILDTOOL_EXPORT_DEPENDS )
set(clear_costmap_recovery_EXEC_DEPENDS "roscpp" "tf" "costmap_2d" "nav_core" "pluginlib" "eigen")
set(clear_costmap_recovery_RUN_DEPENDS "roscpp" "tf" "costmap_2d" "nav_core" "pluginlib" "eigen")
set(clear_costmap_recovery_TEST_DEPENDS )
set(clear_costmap_recovery_DOC_DEPENDS )
set(clear_costmap_recovery_DEPRECATED "")