set(_CATKIN_CURRENT_PACKAGE "vision_opencv")
set(vision_opencv_VERSION "1.12.2")
set(vision_opencv_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(vision_opencv_PACKAGE_FORMAT "1")
set(vision_opencv_BUILD_DEPENDS )
set(vision_opencv_BUILD_EXPORT_DEPENDS "cv_bridge" "image_geometry")
set(vision_opencv_BUILDTOOL_DEPENDS "catkin")
set(vision_opencv_BUILDTOOL_EXPORT_DEPENDS )
set(vision_opencv_EXEC_DEPENDS "cv_bridge" "image_geometry")
set(vision_opencv_RUN_DEPENDS "cv_bridge" "image_geometry")
set(vision_opencv_TEST_DEPENDS )
set(vision_opencv_DOC_DEPENDS )
set(vision_opencv_DEPRECATED "")