set(_CATKIN_CURRENT_PACKAGE "racecar_control")
set(racecar_control_VERSION "0.0.0")
set(racecar_control_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(racecar_control_PACKAGE_FORMAT "1")
set(racecar_control_BUILD_DEPENDS )
set(racecar_control_BUILD_EXPORT_DEPENDS )
set(racecar_control_BUILDTOOL_DEPENDS "catkin")
set(racecar_control_BUILDTOOL_EXPORT_DEPENDS )
set(racecar_control_EXEC_DEPENDS )
set(racecar_control_RUN_DEPENDS )
set(racecar_control_TEST_DEPENDS )
set(racecar_control_DOC_DEPENDS )
set(racecar_control_DEPRECATED "")