set(_CATKIN_CURRENT_PACKAGE "racecar_description")
set(racecar_description_VERSION "0.0.0")
set(racecar_description_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(racecar_description_PACKAGE_FORMAT "1")
set(racecar_description_BUILD_DEPENDS )
set(racecar_description_BUILD_EXPORT_DEPENDS )
set(racecar_description_BUILDTOOL_DEPENDS "catkin")
set(racecar_description_BUILDTOOL_EXPORT_DEPENDS )
set(racecar_description_EXEC_DEPENDS )
set(racecar_description_RUN_DEPENDS )
set(racecar_description_TEST_DEPENDS )
set(racecar_description_DOC_DEPENDS )
set(racecar_description_DEPRECATED "")