set(_CATKIN_CURRENT_PACKAGE "hector_map_server")
set(hector_map_server_VERSION "0.3.5")
set(hector_map_server_MAINTAINER "Johannes Meyer <meyer@fsr.tu-darmstadt.de>")
set(hector_map_server_PACKAGE_FORMAT "1")
set(hector_map_server_BUILD_DEPENDS "roscpp" "hector_map_tools" "hector_marker_drawing" "hector_nav_msgs" "nav_msgs" "tf")
set(hector_map_server_BUILD_EXPORT_DEPENDS "roscpp" "hector_map_tools" "hector_marker_drawing" "hector_nav_msgs" "nav_msgs" "tf")
set(hector_map_server_BUILDTOOL_DEPENDS "catkin")
set(hector_map_server_BUILDTOOL_EXPORT_DEPENDS )
set(hector_map_server_EXEC_DEPENDS "roscpp" "hector_map_tools" "hector_marker_drawing" "hector_nav_msgs" "nav_msgs" "tf")
set(hector_map_server_RUN_DEPENDS "roscpp" "hector_map_tools" "hector_marker_drawing" "hector_nav_msgs" "nav_msgs" "tf")
set(hector_map_server_TEST_DEPENDS )
set(hector_map_server_DOC_DEPENDS )
set(hector_map_server_DEPRECATED "")