set(_CATKIN_CURRENT_PACKAGE "laser_scan_splitter")
set(laser_scan_splitter_VERSION "0.3.2")
set(laser_scan_splitter_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(laser_scan_splitter_PACKAGE_FORMAT "1")
set(laser_scan_splitter_BUILD_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_splitter_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_splitter_BUILDTOOL_DEPENDS "catkin")
set(laser_scan_splitter_BUILDTOOL_EXPORT_DEPENDS )
set(laser_scan_splitter_EXEC_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_splitter_RUN_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_splitter_TEST_DEPENDS )
set(laser_scan_splitter_DOC_DEPENDS )
set(laser_scan_splitter_DEPRECATED "")