set(_CATKIN_CURRENT_PACKAGE "robot_pose_ekf")
set(robot_pose_ekf_VERSION "1.13.1")
set(robot_pose_ekf_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(robot_pose_ekf_PACKAGE_FORMAT "1")
set(robot_pose_ekf_BUILD_DEPENDS "roscpp" "rostest" "bfl" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "tf")
set(robot_pose_ekf_BUILD_EXPORT_DEPENDS "roscpp" "rostest" "bfl" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "tf")
set(robot_pose_ekf_BUILDTOOL_DEPENDS "catkin")
set(robot_pose_ekf_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(robot_pose_ekf_BUILDTOOL_EXPORT_DEPENDS )
set(robot_pose_ekf_EXEC_DEPENDS "roscpp" "rostest" "bfl" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "tf")
set(robot_pose_ekf_RUN_DEPENDS "roscpp" "rostest" "bfl" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "tf")
set(robot_pose_ekf_TEST_DEPENDS "rosbag")
set(robot_pose_ekf_DOC_DEPENDS )
set(robot_pose_ekf_DEPRECATED "")