set(_CATKIN_CURRENT_PACKAGE "cv_bridge")
set(cv_bridge_VERSION "1.12.2")
set(cv_bridge_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(cv_bridge_PACKAGE_FORMAT "2")
set(cv_bridge_BUILD_DEPENDS "boost" "opencv3" "python" "rosconsole" "sensor_msgs")
set(cv_bridge_BUILD_EXPORT_DEPENDS "sensor_msgs")
set(cv_bridge_BUILDTOOL_DEPENDS "catkin")
set(cv_bridge_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(cv_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(cv_bridge_EXEC_DEPENDS "boost" "opencv3" "python" "rosconsole")
set(cv_bridge_RUN_DEPENDS "boost" "opencv3" "python" "rosconsole" "sensor_msgs")
set(cv_bridge_TEST_DEPENDS "rostest" "python-numpy")
set(cv_bridge_DOC_DEPENDS "dvipng")
set(cv_bridge_DEPRECATED "")