set(cv_bridge_SETUP_PY_VERSION "1.12.2")
set(cv_bridge_SETUP_PY_SCRIPTS "")
set(cv_bridge_SETUP_PY_PACKAGES "cv_bridge")
set(cv_bridge_SETUP_PY_PACKAGE_DIRS "python/cv_bridge")
set(cv_bridge_SETUP_PY_MODULES "")
set(cv_bridge_SETUP_PY_MODULE_DIRS "")