set(_CATKIN_CURRENT_PACKAGE "hector_geotiff")
set(hector_geotiff_VERSION "0.3.5")
set(hector_geotiff_MAINTAINER "Johannes Meyer <meyer@fsr.tu-darmstadt.de>")
set(hector_geotiff_PACKAGE_FORMAT "1")
set(hector_geotiff_BUILD_DEPENDS "hector_map_tools" "hector_nav_msgs" "nav_msgs" "pluginlib" "roscpp" "std_msgs" "libqt4-dev")
set(hector_geotiff_BUILD_EXPORT_DEPENDS "hector_map_tools" "hector_nav_msgs" "nav_msgs" "pluginlib" "roscpp" "std_msgs" "libqt4-dev")
set(hector_geotiff_BUILDTOOL_DEPENDS "catkin")
set(hector_geotiff_BUILDTOOL_EXPORT_DEPENDS )
set(hector_geotiff_EXEC_DEPENDS "hector_map_tools" "hector_nav_msgs" "nav_msgs" "pluginlib" "roscpp" "std_msgs" "libqt4-dev")
set(hector_geotiff_RUN_DEPENDS "hector_map_tools" "hector_nav_msgs" "nav_msgs" "pluginlib" "roscpp" "std_msgs" "libqt4-dev")
set(hector_geotiff_TEST_DEPENDS )
set(hector_geotiff_DOC_DEPENDS )
set(hector_geotiff_DEPRECATED "")