set(_CATKIN_CURRENT_PACKAGE "carrot_planner")
set(carrot_planner_VERSION "1.13.1")
set(carrot_planner_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(carrot_planner_PACKAGE_FORMAT "1")
set(carrot_planner_BUILD_DEPENDS "roscpp" "costmap_2d" "pluginlib" "nav_core" "base_local_planner" "tf" "eigen")
set(carrot_planner_BUILD_EXPORT_DEPENDS "roscpp" "costmap_2d" "pluginlib" "nav_core" "base_local_planner" "tf" "eigen")
set(carrot_planner_BUILDTOOL_DEPENDS "catkin")
set(carrot_planner_BUILDTOOL_EXPORT_DEPENDS )
set(carrot_planner_EXEC_DEPENDS "roscpp" "costmap_2d" "pluginlib" "nav_core" "base_local_planner" "tf" "eigen")
set(carrot_planner_RUN_DEPENDS "roscpp" "costmap_2d" "pluginlib" "nav_core" "base_local_planner" "tf" "eigen")
set(carrot_planner_TEST_DEPENDS )
set(carrot_planner_DOC_DEPENDS )
set(carrot_planner_DEPRECATED "")