set(_CATKIN_CURRENT_PACKAGE "rosserial_client")
set(rosserial_client_VERSION "0.6.4")
set(rosserial_client_MAINTAINER "Paul Bouchier <paul.bouchier@gmail.com>, Mike Purvis <mpurvis@clearpathrobotics.com>")
set(rosserial_client_PACKAGE_FORMAT "1")
set(rosserial_client_BUILD_DEPENDS )
set(rosserial_client_BUILD_EXPORT_DEPENDS "std_msgs" "rosserial_msgs" "rospy" "tf")
set(rosserial_client_BUILDTOOL_DEPENDS "catkin")
set(rosserial_client_BUILDTOOL_EXPORT_DEPENDS )
set(rosserial_client_EXEC_DEPENDS "std_msgs" "rosserial_msgs" "rospy" "tf")
set(rosserial_client_RUN_DEPENDS "std_msgs" "rosserial_msgs" "rospy" "tf")
set(rosserial_client_TEST_DEPENDS )
set(rosserial_client_DOC_DEPENDS )
set(rosserial_client_DEPRECATED "")