set(_CATKIN_CURRENT_PACKAGE "laser_scan_sparsifier")
set(laser_scan_sparsifier_VERSION "0.3.2")
set(laser_scan_sparsifier_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(laser_scan_sparsifier_PACKAGE_FORMAT "1")
set(laser_scan_sparsifier_BUILD_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_sparsifier_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_sparsifier_BUILDTOOL_DEPENDS "catkin")
set(laser_scan_sparsifier_BUILDTOOL_EXPORT_DEPENDS )
set(laser_scan_sparsifier_EXEC_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_sparsifier_RUN_DEPENDS "roscpp" "nodelet" "sensor_msgs")
set(laser_scan_sparsifier_TEST_DEPENDS )
set(laser_scan_sparsifier_DOC_DEPENDS )
set(laser_scan_sparsifier_DEPRECATED "")