set(_CATKIN_CURRENT_PACKAGE "scan_to_cloud_converter")
set(scan_to_cloud_converter_VERSION "0.3.2")
set(scan_to_cloud_converter_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(scan_to_cloud_converter_PACKAGE_FORMAT "1")
set(scan_to_cloud_converter_BUILD_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "libpcl-all-dev")
set(scan_to_cloud_converter_BUILD_EXPORT_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "libpcl-all")
set(scan_to_cloud_converter_BUILDTOOL_DEPENDS "catkin")
set(scan_to_cloud_converter_BUILDTOOL_EXPORT_DEPENDS )
set(scan_to_cloud_converter_EXEC_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "libpcl-all")
set(scan_to_cloud_converter_RUN_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "libpcl-all")
set(scan_to_cloud_converter_TEST_DEPENDS )
set(scan_to_cloud_converter_DOC_DEPENDS )
set(scan_to_cloud_converter_DEPRECATED "")