set(_CATKIN_CURRENT_PACKAGE "slam_gmapping")
set(slam_gmapping_VERSION "1.3.8")
set(slam_gmapping_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(slam_gmapping_PACKAGE_FORMAT "1")
set(slam_gmapping_BUILD_DEPENDS )
set(slam_gmapping_BUILD_EXPORT_DEPENDS "openslam_gmapping" "gmapping")
set(slam_gmapping_BUILDTOOL_DEPENDS "catkin")
set(slam_gmapping_BUILDTOOL_EXPORT_DEPENDS )
set(slam_gmapping_EXEC_DEPENDS "openslam_gmapping" "gmapping")
set(slam_gmapping_RUN_DEPENDS "openslam_gmapping" "gmapping")
set(slam_gmapping_TEST_DEPENDS )
set(slam_gmapping_DOC_DEPENDS )
set(slam_gmapping_DEPRECATED "")