set(_CATKIN_CURRENT_PACKAGE "hector_imu_tools")
set(hector_imu_tools_VERSION "0.3.5")
set(hector_imu_tools_MAINTAINER "Johannes Meyer <meyer@fsr.tu-darmstadt.de>")
set(hector_imu_tools_PACKAGE_FORMAT "1")
set(hector_imu_tools_BUILD_DEPENDS "roscpp" "tf" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(hector_imu_tools_BUILD_EXPORT_DEPENDS "roscpp" "tf" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(hector_imu_tools_BUILDTOOL_DEPENDS "catkin")
set(hector_imu_tools_BUILDTOOL_EXPORT_DEPENDS )
set(hector_imu_tools_EXEC_DEPENDS "roscpp" "tf" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(hector_imu_tools_RUN_DEPENDS "roscpp" "tf" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(hector_imu_tools_TEST_DEPENDS )
set(hector_imu_tools_DOC_DEPENDS )
set(hector_imu_tools_DEPRECATED "")