set(_CATKIN_CURRENT_PACKAGE "hector_geotiff_plugins")
set(hector_geotiff_plugins_VERSION "0.3.5")
set(hector_geotiff_plugins_MAINTAINER "Johannes Meyer <meyer@fsr.tu-darmstadt.de>")
set(hector_geotiff_plugins_PACKAGE_FORMAT "1")
set(hector_geotiff_plugins_BUILD_DEPENDS "hector_geotiff" "hector_nav_msgs")
set(hector_geotiff_plugins_BUILD_EXPORT_DEPENDS "hector_geotiff" "hector_nav_msgs")
set(hector_geotiff_plugins_BUILDTOOL_DEPENDS "catkin")
set(hector_geotiff_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(hector_geotiff_plugins_EXEC_DEPENDS "hector_geotiff" "hector_nav_msgs")
set(hector_geotiff_plugins_RUN_DEPENDS "hector_geotiff" "hector_nav_msgs")
set(hector_geotiff_plugins_TEST_DEPENDS )
set(hector_geotiff_plugins_DOC_DEPENDS )
set(hector_geotiff_plugins_DEPRECATED "")