set(_CATKIN_CURRENT_PACKAGE "joy")
set(joy_VERSION "1.10.1")
set(joy_MAINTAINER "Jonathan Bohren <jbo@jhu.edu>")
set(joy_PACKAGE_FORMAT "1")
set(joy_BUILD_DEPENDS "roscpp" "diagnostic_updater" "sensor_msgs" "joystick")
set(joy_BUILD_EXPORT_DEPENDS "roscpp" "diagnostic_updater" "sensor_msgs" "joystick")
set(joy_BUILDTOOL_DEPENDS "catkin")
set(joy_BUILDTOOL_EXPORT_DEPENDS )
set(joy_EXEC_DEPENDS "roscpp" "diagnostic_updater" "sensor_msgs" "joystick")
set(joy_RUN_DEPENDS "roscpp" "diagnostic_updater" "sensor_msgs" "joystick")
set(joy_TEST_DEPENDS "rosbag")
set(joy_DOC_DEPENDS )
set(joy_DEPRECATED "")