set(_CATKIN_CURRENT_PACKAGE "voxel_grid")
set(voxel_grid_VERSION "1.13.1")
set(voxel_grid_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(voxel_grid_PACKAGE_FORMAT "1")
set(voxel_grid_BUILD_DEPENDS "roscpp")
set(voxel_grid_BUILD_EXPORT_DEPENDS "roscpp")
set(voxel_grid_BUILDTOOL_DEPENDS "catkin")
set(voxel_grid_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(voxel_grid_BUILDTOOL_EXPORT_DEPENDS )
set(voxel_grid_EXEC_DEPENDS "roscpp")
set(voxel_grid_RUN_DEPENDS "roscpp")
set(voxel_grid_TEST_DEPENDS )
set(voxel_grid_DOC_DEPENDS )
set(voxel_grid_DEPRECATED "")