set(_CATKIN_CURRENT_PACKAGE "loco")
set(loco_VERSION "1.0.0")
set(loco_MAINTAINER "Kazu Otani <kazuotani14@gmail.com>")
set(loco_PACKAGE_FORMAT "1")
set(loco_BUILD_DEPENDS "roscpp" "std_msgs" "tf" "move_base_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(loco_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "tf" "move_base_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(loco_BUILDTOOL_DEPENDS "catkin")
set(loco_BUILDTOOL_EXPORT_DEPENDS )
set(loco_EXEC_DEPENDS "roscpp" "std_msgs" "tf" "move_base_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(loco_RUN_DEPENDS "roscpp" "std_msgs" "tf" "move_base_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(loco_TEST_DEPENDS )
set(loco_DOC_DEPENDS )
set(loco_DEPRECATED "")