set(_CATKIN_CURRENT_PACKAGE "racecar_simulator")
set(racecar_simulator_VERSION "0.0.1")
set(racecar_simulator_MAINTAINER "Abhishek Agarwal <abhia@mit.edu>")
set(racecar_simulator_PACKAGE_FORMAT "1")
set(racecar_simulator_BUILD_DEPENDS )
set(racecar_simulator_BUILD_EXPORT_DEPENDS )
set(racecar_simulator_BUILDTOOL_DEPENDS "catkin")
set(racecar_simulator_BUILDTOOL_EXPORT_DEPENDS )
set(racecar_simulator_EXEC_DEPENDS )
set(racecar_simulator_RUN_DEPENDS )
set(racecar_simulator_TEST_DEPENDS )
set(racecar_simulator_DOC_DEPENDS )
set(racecar_simulator_DEPRECATED "")