set(_CATKIN_CURRENT_PACKAGE "urg_node")
set(urg_node_VERSION "0.1.9")
set(urg_node_MAINTAINER "Chad Rockey <chadrockey@gmail.com>")
set(urg_node_PACKAGE_FORMAT "1")
set(urg_node_BUILD_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "urg_c" "nodelet" "dynamic_reconfigure" "tf" "laser_proc" "diagnostic_updater")
set(urg_node_BUILD_EXPORT_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "urg_c" "nodelet" "dynamic_reconfigure" "tf" "laser_proc" "diagnostic_updater")
set(urg_node_BUILDTOOL_DEPENDS "catkin")
set(urg_node_BUILDTOOL_EXPORT_DEPENDS )
set(urg_node_EXEC_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "urg_c" "nodelet" "dynamic_reconfigure" "tf" "laser_proc" "diagnostic_updater")
set(urg_node_RUN_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "urg_c" "nodelet" "dynamic_reconfigure" "tf" "laser_proc" "diagnostic_updater")
set(urg_node_TEST_DEPENDS )
set(urg_node_DOC_DEPENDS )
set(urg_node_DEPRECATED "")