set(_CATKIN_CURRENT_PACKAGE "gmapping")
set(gmapping_VERSION "1.3.8")
set(gmapping_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(gmapping_PACKAGE_FORMAT "1")
set(gmapping_BUILD_DEPENDS "nav_msgs" "openslam_gmapping" "roscpp" "rostest" "tf")
set(gmapping_BUILD_EXPORT_DEPENDS "nav_msgs" "openslam_gmapping" "roscpp" "tf")
set(gmapping_BUILDTOOL_DEPENDS "catkin")
set(gmapping_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(gmapping_BUILDTOOL_EXPORT_DEPENDS )
set(gmapping_EXEC_DEPENDS "nav_msgs" "openslam_gmapping" "roscpp" "tf")
set(gmapping_RUN_DEPENDS "nav_msgs" "openslam_gmapping" "roscpp" "tf")
set(gmapping_TEST_DEPENDS )
set(gmapping_DOC_DEPENDS )
set(gmapping_DEPRECATED "")