set(_CATKIN_CURRENT_PACKAGE "map_server")
set(map_server_VERSION "1.13.1")
set(map_server_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(map_server_PACKAGE_FORMAT "1")
set(map_server_BUILD_DEPENDS "nav_msgs" "roscpp" "rostest" "sdl-image" "tf" "yaml-cpp")
set(map_server_BUILD_EXPORT_DEPENDS "nav_msgs" "roscpp" "rostest" "sdl-image" "tf" "yaml-cpp")
set(map_server_BUILDTOOL_DEPENDS "catkin")
set(map_server_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(map_server_BUILDTOOL_EXPORT_DEPENDS )
set(map_server_EXEC_DEPENDS "nav_msgs" "roscpp" "rostest" "sdl-image" "tf" "yaml-cpp")
set(map_server_RUN_DEPENDS "nav_msgs" "roscpp" "rostest" "sdl-image" "tf" "yaml-cpp")
set(map_server_TEST_DEPENDS "rospy")
set(map_server_DOC_DEPENDS )
set(map_server_DEPRECATED "")