set(_CATKIN_CURRENT_PACKAGE "teleop_twist_joy")
set(teleop_twist_joy_VERSION "0.1.2")
set(teleop_twist_joy_MAINTAINER "Mike Purvis <mpurvis@clearpathrobotics.com>")
set(teleop_twist_joy_PACKAGE_FORMAT "1")
set(teleop_twist_joy_BUILD_DEPENDS "geometry_msgs" "joy" "roscpp" "roslaunch" "roslint" "rostest" "sensor_msgs")
set(teleop_twist_joy_BUILD_EXPORT_DEPENDS "geometry_msgs" "joy" "roscpp" "sensor_msgs")
set(teleop_twist_joy_BUILDTOOL_DEPENDS "catkin")
set(teleop_twist_joy_BUILDTOOL_EXPORT_DEPENDS )
set(teleop_twist_joy_EXEC_DEPENDS "geometry_msgs" "joy" "roscpp" "sensor_msgs")
set(teleop_twist_joy_RUN_DEPENDS "geometry_msgs" "joy" "roscpp" "sensor_msgs")
set(teleop_twist_joy_TEST_DEPENDS )
set(teleop_twist_joy_DOC_DEPENDS )
set(teleop_twist_joy_DEPRECATED "")