set(_CATKIN_CURRENT_PACKAGE "polar_scan_matcher")
set(polar_scan_matcher_VERSION "0.3.2")
set(polar_scan_matcher_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>")
set(polar_scan_matcher_PACKAGE_FORMAT "1")
set(polar_scan_matcher_BUILD_DEPENDS "tf" "roscpp" "sensor_msgs" "geometry_msgs")
set(polar_scan_matcher_BUILD_EXPORT_DEPENDS "tf" "roscpp" "sensor_msgs" "geometry_msgs")
set(polar_scan_matcher_BUILDTOOL_DEPENDS "catkin")
set(polar_scan_matcher_BUILDTOOL_EXPORT_DEPENDS )
set(polar_scan_matcher_EXEC_DEPENDS "tf" "roscpp" "sensor_msgs" "geometry_msgs")
set(polar_scan_matcher_RUN_DEPENDS "tf" "roscpp" "sensor_msgs" "geometry_msgs")
set(polar_scan_matcher_TEST_DEPENDS )
set(polar_scan_matcher_DOC_DEPENDS )
set(polar_scan_matcher_DEPRECATED "")