set(_CATKIN_CURRENT_PACKAGE "opencv_tests")
set(opencv_tests_VERSION "1.12.2")
set(opencv_tests_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(opencv_tests_PACKAGE_FORMAT "1")
set(opencv_tests_BUILD_DEPENDS )
set(opencv_tests_BUILD_EXPORT_DEPENDS "cv_bridge")
set(opencv_tests_BUILDTOOL_DEPENDS "catkin")
set(opencv_tests_BUILDTOOL_EXPORT_DEPENDS )
set(opencv_tests_EXEC_DEPENDS "cv_bridge")
set(opencv_tests_RUN_DEPENDS "cv_bridge")
set(opencv_tests_TEST_DEPENDS )
set(opencv_tests_DOC_DEPENDS )
set(opencv_tests_DEPRECATED "")