set(_CATKIN_CURRENT_PACKAGE "laser_scan_matcher")
set(laser_scan_matcher_VERSION "0.3.2")
set(laser_scan_matcher_MAINTAINER "Ivan Dryanovski <ccnyroboticslab@gmail.com>, Carlos <cjaramillo@gc.cuny.edu>, Isaac I.Y. Saito <dev@opensource-robotics.tokyo.jp>")
set(laser_scan_matcher_PACKAGE_FORMAT "1")
set(laser_scan_matcher_BUILD_DEPENDS "csm" "geometry_msgs" "libpcl-all-dev" "nav_msgs" "nodelet" "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "tf")
set(laser_scan_matcher_BUILD_EXPORT_DEPENDS "csm" "geometry_msgs" "libpcl-all" "nav_msgs" "nodelet" "pcl_ros" "pcl_conversions" "roscpp" "sensor_msgs" "tf")
set(laser_scan_matcher_BUILDTOOL_DEPENDS "catkin")
set(laser_scan_matcher_BUILDTOOL_EXPORT_DEPENDS )
set(laser_scan_matcher_EXEC_DEPENDS "csm" "geometry_msgs" "libpcl-all" "nav_msgs" "nodelet" "pcl_ros" "pcl_conversions" "roscpp" "sensor_msgs" "tf")
set(laser_scan_matcher_RUN_DEPENDS "csm" "geometry_msgs" "libpcl-all" "nav_msgs" "nodelet" "pcl_ros" "pcl_conversions" "roscpp" "sensor_msgs" "tf")
set(laser_scan_matcher_TEST_DEPENDS )
set(laser_scan_matcher_DOC_DEPENDS )
set(laser_scan_matcher_DEPRECATED "")