set(_CATKIN_CURRENT_PACKAGE "joystick_drivers")
set(joystick_drivers_VERSION "1.10.1")
set(joystick_drivers_MAINTAINER "Jonathan Bohren <jbo@jhu.edu>")
set(joystick_drivers_PACKAGE_FORMAT "1")
set(joystick_drivers_BUILD_DEPENDS )
set(joystick_drivers_BUILD_EXPORT_DEPENDS "joy" "ps3joy" "spacenav_node" "wiimote")
set(joystick_drivers_BUILDTOOL_DEPENDS "catkin")
set(joystick_drivers_BUILDTOOL_EXPORT_DEPENDS )
set(joystick_drivers_EXEC_DEPENDS "joy" "ps3joy" "spacenav_node" "wiimote")
set(joystick_drivers_RUN_DEPENDS "joy" "ps3joy" "spacenav_node" "wiimote")
set(joystick_drivers_TEST_DEPENDS )
set(joystick_drivers_DOC_DEPENDS )
set(joystick_drivers_DEPRECATED "")