set(_CATKIN_CURRENT_PACKAGE "navigation")
set(navigation_VERSION "1.13.1")
set(navigation_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(navigation_PACKAGE_FORMAT "1")
set(navigation_BUILD_DEPENDS )
set(navigation_BUILD_EXPORT_DEPENDS "amcl" "carrot_planner" "dwa_local_planner" "move_base" "nav_core" "robot_pose_ekf" "base_local_planner" "clear_costmap_recovery" "fake_localization" "global_planner" "move_base_msgs" "navfn" "rotate_recovery" "costmap_2d" "map_server" "move_slow_and_clear" "voxel_grid")
set(navigation_BUILDTOOL_DEPENDS "catkin")
set(navigation_BUILDTOOL_EXPORT_DEPENDS )
set(navigation_EXEC_DEPENDS "amcl" "carrot_planner" "dwa_local_planner" "move_base" "nav_core" "robot_pose_ekf" "base_local_planner" "clear_costmap_recovery" "fake_localization" "global_planner" "move_base_msgs" "navfn" "rotate_recovery" "costmap_2d" "map_server" "move_slow_and_clear" "voxel_grid")
set(navigation_RUN_DEPENDS "amcl" "carrot_planner" "dwa_local_planner" "move_base" "nav_core" "robot_pose_ekf" "base_local_planner" "clear_costmap_recovery" "fake_localization" "global_planner" "move_base_msgs" "navfn" "rotate_recovery" "costmap_2d" "map_server" "move_slow_and_clear" "voxel_grid")
set(navigation_TEST_DEPENDS )
set(navigation_DOC_DEPENDS )
set(navigation_DEPRECATED "")