set(_CATKIN_CURRENT_PACKAGE "amcl")
set(amcl_VERSION "1.13.1")
set(amcl_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(amcl_PACKAGE_FORMAT "1")
set(amcl_BUILD_DEPENDS "rosbag" "dynamic_reconfigure" "message_filters" "nav_msgs" "roscpp" "rostest" "std_srvs" "tf")
set(amcl_BUILD_EXPORT_DEPENDS "rosbag" "roscpp" "dynamic_reconfigure" "tf" "nav_msgs")
set(amcl_BUILDTOOL_DEPENDS "catkin")
set(amcl_BUILDTOOL_EXPORT_DEPENDS )
set(amcl_EXEC_DEPENDS "rosbag" "roscpp" "dynamic_reconfigure" "tf" "nav_msgs")
set(amcl_RUN_DEPENDS "rosbag" "roscpp" "dynamic_reconfigure" "tf" "nav_msgs")
set(amcl_TEST_DEPENDS "map_server")
set(amcl_DOC_DEPENDS )
set(amcl_DEPRECATED "")