set(_CATKIN_CURRENT_PACKAGE "base_local_planner")
set(base_local_planner_VERSION "1.13.1")
set(base_local_planner_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>, Michael Ferguson <mferguson@fetchrobotics.com>")
set(base_local_planner_PACKAGE_FORMAT "1")
set(base_local_planner_BUILD_DEPENDS "cmake_modules" "std_msgs" "nav_msgs" "rosconsole" "roscpp" "tf" "rospy" "pluginlib" "costmap_2d" "voxel_grid" "angles" "visualization_msgs" "geometry_msgs" "nav_core" "pcl_conversions" "pcl_ros" "eigen" "dynamic_reconfigure" "message_generation")
set(base_local_planner_BUILD_EXPORT_DEPENDS "std_msgs" "nav_msgs" "rosconsole" "roscpp" "tf" "rospy" "pluginlib" "costmap_2d" "voxel_grid" "angles" "visualization_msgs" "geometry_msgs" "nav_core" "pcl_ros" "eigen" "dynamic_reconfigure" "message_generation")
set(base_local_planner_BUILDTOOL_DEPENDS "catkin")
set(base_local_planner_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(base_local_planner_BUILDTOOL_EXPORT_DEPENDS )
set(base_local_planner_EXEC_DEPENDS "std_msgs" "nav_msgs" "rosconsole" "roscpp" "tf" "rospy" "pluginlib" "costmap_2d" "voxel_grid" "angles" "visualization_msgs" "geometry_msgs" "nav_core" "pcl_ros" "eigen" "dynamic_reconfigure" "message_generation")
set(base_local_planner_RUN_DEPENDS "std_msgs" "nav_msgs" "rosconsole" "roscpp" "tf" "rospy" "pluginlib" "costmap_2d" "voxel_grid" "angles" "visualization_msgs" "geometry_msgs" "nav_core" "pcl_ros" "eigen" "dynamic_reconfigure" "message_generation")
set(base_local_planner_TEST_DEPENDS )
set(base_local_planner_DOC_DEPENDS )
set(base_local_planner_DEPRECATED "")