set(base_local_planner_SETUP_PY_VERSION "1.13.1")
set(base_local_planner_SETUP_PY_SCRIPTS "")
set(base_local_planner_SETUP_PY_PACKAGES "local_planner_limits")
set(base_local_planner_SETUP_PY_PACKAGE_DIRS "src/local_planner_limits")
set(base_local_planner_SETUP_PY_MODULES "")
set(base_local_planner_SETUP_PY_MODULE_DIRS "")